/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import controllers.SessionController;
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPopupMenu;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import models.Articulo;
import models.Factura;

/**
 *
 * @author alvaro
 */
public class TableForeings extends javax.swing.JPanel {
    private final SessionController session_ctrl = new SessionController();
    private String[] columns_name;
    private List registers_list;
    private String id;
    private String table;
    private String table_selected;
    
    /**
     * Creates new form TableForeings
     */
    public TableForeings(String id, String table, String table_selected) {
        initComponents();
        this.id = id;
        this.table = table;
        this.table_selected = table_selected;
        refreshTableTrue();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtable_foreings = new javax.swing.JTable();
        title_table = new javax.swing.JLabel();
        add = new javax.swing.JButton();
        dropdown = new javax.swing.JComboBox<>();

        jtable_foreings.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtable_foreings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtable_foreingsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtable_foreings);

        title_table.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        title_table.setText("jLabel1");

        add.setText("jButton1");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        dropdown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 609, Short.MAX_VALUE)
                .addGap(15, 15, 15))
            .addGroup(layout.createSequentialGroup()
                .addGap(265, 265, 265)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(title_table)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(add)
                        .addGap(21, 21, 21)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(dropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(285, 285, 285))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title_table)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(dropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(add)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jtable_foreingsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtable_foreingsMouseClicked
        // TODO add your handling code here:
        if (SwingUtilities.isRightMouseButton(evt)) {
            int row = jtable_foreings.rowAtPoint(evt.getPoint());

            showPopUp(evt.getComponent(), evt.getX(), evt.getY(), row, String.valueOf(jtable_foreings.getValueAt(row, 0)), id);
        }
    }//GEN-LAST:event_jtable_foreingsMouseClicked

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
        if(!session_ctrl.associateRegister(String.valueOf(dropdown.getSelectedItem()).split("-")[0].trim(), id, table_selected))
            new DialogMessages("Registro ya asociado", "El regisro que elegiste ya esta asociado a otro", 1).showMessage();
        refreshTableTrue();
    }//GEN-LAST:event_addActionPerformed

    public void showPopUp(Component component, int x, int y, int selectedRow, String id, String id_table){
        JPopupMenu popup_menu = new JPopupMenu();

        JMenuItem delete = new JMenuItem("Desasociar");
        delete.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                int result = new DialogMessages("Desasociar registro", "¿Desea desasociar el registro " + id + " ?", 2).showMessageConfirm();
                if(result == JOptionPane.OK_OPTION){
                    session_ctrl.disassociateRegister(id, id_table, table_selected);
                    refreshTableTrue();
                }
            }
        });
        
        popup_menu.add(delete);

        popup_menu.show(component, x, y);
    }
    
        public void updateTable(Boolean modify_columns) {
        DefaultTableModel model = (DefaultTableModel) jtable_foreings.getModel();
        
        if(modify_columns){
            model.setColumnCount(0);
            
            for(String column : columns_name){
                model.addColumn(column);
            }
        }
        
        model.setRowCount(0);

        for(Object register : registers_list){
            if(register instanceof Factura){
                Object[] rowData = ((Factura) register).convertToObjectArray();
                rowData[rowData.length - 1] = null;
                model.addRow(rowData);
            }else if(register instanceof Articulo){
                Object[] rowData = ((Articulo) register).convertToObjectArray();
                rowData[rowData.length - 1] = null;
                model.addRow(rowData);
            }
        }
    }
    
    public void updateDropdown(){
        dropdown.removeAllItems();
        
        List others = session_ctrl.getOthers(id, table_selected);
        
        for(Object register : others){
            dropdown.addItem(register.toString());
        }
    }
    
    public void refreshTableTrue(){
        registers_list = session_ctrl.getTableById(id, table_selected);

        if(table.equals("facturas")){
            columns_name = new String[]{"número", "fecha"};
        }else{
            columns_name = new String[]{"código", "nombre"};
        }
        updateTable(true);
        updateDropdown();
        title_table.setText(table);
        add.setText("asociar " + table.substring(0, table.length() - 1));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JComboBox<String> dropdown;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtable_foreings;
    private javax.swing.JLabel title_table;
    // End of variables declaration//GEN-END:variables
}
